from typing import Final

ITEM_CREATED: Final = "ITEM_CREATED"
AI_DRAFT_GENERATION_STARTED: Final = "AI_DRAFT_GENERATION_STARTED"
AI_DRAFT_GENERATED: Final = "AI_DRAFT_GENERATED"
AI_DRAFT_GENERATION_FAILED: Final = "AI_DRAFT_GENERATION_FAILED"
DRAFT_REGENERATION_STARTED: Final = "DRAFT_REGENERATION_STARTED"
DRAFT_REGENERATED: Final = "DRAFT_REGENERATED"
DRAFT_REGENERATION_FAILED: Final = "DRAFT_REGENERATION_FAILED"
DRAFT_EDITED: Final = "DRAFT_EDITED"
ITEM_APPROVED: Final = "ITEM_APPROVED"
ITEM_REJECTED: Final = "ITEM_REJECTED"
JOB_STARTED: Final = "JOB_STARTED"
JOB_COMPLETED: Final = "JOB_COMPLETED"
JOB_FAILED: Final = "JOB_FAILED"
RUNTIME_PROVIDER_CHANGED: Final = "RUNTIME_PROVIDER_CHANGED"

AUDIT_ACTIONS: Final[tuple[str, ...]] = (
    ITEM_CREATED,
    AI_DRAFT_GENERATION_STARTED,
    AI_DRAFT_GENERATED,
    AI_DRAFT_GENERATION_FAILED,
    DRAFT_REGENERATION_STARTED,
    DRAFT_REGENERATED,
    DRAFT_REGENERATION_FAILED,
    DRAFT_EDITED,
    ITEM_APPROVED,
    ITEM_REJECTED,
    JOB_STARTED,
    JOB_COMPLETED,
    JOB_FAILED,
    RUNTIME_PROVIDER_CHANGED,
)


def audit_action_check_sql(column_name: str = "action") -> str:
    allowed_values = ", ".join(f"'{action}'" for action in AUDIT_ACTIONS)
    return f"{column_name} IN ({allowed_values})"
